USE electronic_store;

DROP TABLE IF EXISTS orders_products;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS statuses;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS categories;

CREATE TABLE roles
(
    id   INT UNSIGNED NOT NULL,
    name VARCHAR(10)  NOT NULL UNIQUE,
    PRIMARY KEY (id)
) ENGINE = INNODB,
  CHARACTER SET utf8,
  COLLATE utf8_bin;

CREATE TABLE users
(
    id       INT UNSIGNED NOT NULL AUTO_INCREMENT,
    email    VARCHAR(30)  NOT NULL UNIQUE,
    password VARCHAR(30)  NOT NULL,
    roleId   INT UNSIGNED NOT NULL,
    name     VARCHAR(30) DEFAULT NULL,
    surname  VARCHAR(30) DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT `roleId=id` FOREIGN KEY (roleId) REFERENCES roles (id)
) ENGINE = INNODB,
  CHARACTER SET utf8,
  COLLATE utf8_bin;

CREATE TABLE statuses
(
    id   INT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(30)  NOT NULL UNIQUE,
    PRIMARY KEY (id)
) ENGINE = INNODB,
  CHARACTER SET utf8,
  COLLATE utf8_bin;

CREATE TABLE orders
(
    id       INT UNSIGNED NOT NULL AUTO_INCREMENT,
    userId   INT UNSIGNED NOT NULL,
    statusId INT UNSIGNED NOT NULL,
    bill     INT UNSIGNED NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT `userId=id` FOREIGN KEY (userId) REFERENCES users (id),
    CONSTRAINT `statusId=id` FOREIGN KEY (statusId) REFERENCES statuses (id)
) ENGINE = INNODB,
  CHARACTER SET utf8,
  COLLATE utf8_bin;

CREATE TABLE categories
(
    id   INT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(30)  NOT NULL UNIQUE,
    PRIMARY KEY (id)
) ENGINE = INNODB,
  CHARACTER SET utf8,
  COLLATE utf8_bin;

CREATE TABLE products
(
    id         INT UNSIGNED NOT NULL AUTO_INCREMENT,
    name       VARCHAR(30)  NOT NULL UNIQUE,
    price      INT UNSIGNED NOT NULL,
    amount     INT UNSIGNED DEFAULT 0,
    categoryId INT UNSIGNED NOT NULL,
    CONSTRAINT `categoryId=id` FOREIGN KEY (categoryId) REFERENCES categories (id),
    PRIMARY KEY (id)
) ENGINE = INNODB,
  CHARACTER SET utf8,
  COLLATE utf8_bin;

CREATE TABLE orders_products
(
    orderId   INT UNSIGNED NOT NULL REFERENCES orders(id),
    productId INT UNSIGNED NOT NULL,
    amount    INT UNSIGNED NOT NULL,
    PRIMARY KEY (orderId, productId),
    CONSTRAINT `productId=id` FOREIGN KEY (productId) REFERENCES products (id)
) ENGINE = INNODB,
  CHARACTER SET utf8,
  COLLATE utf8_bin;


